### ISSUE TITLE
Membership Request for Yuki_Luofan

### ISSUE THREAD

**Issue by Yuki-Luofan** [RinLin-INT-Organization/Membership-Requests#1]
> 明顯的，不想使用模板，所以還是自己寫吧

用戶名：Yuki-Luofan
摘要：建立會員請求
目的：只是接觸
介紹：我是Yuki-Luofan，目前是LainZine的新主編（中國特別版），我真是無聊

**Comment by RinLin-NYA** [comment]
还真有人来啊(

**Comment by RinLin-NYA** [comment]
> > 明顯的，不想使用模板，所以還是自己寫吧
> 
> 用戶名：Yuki-Luofan 摘要：建立會員請求 目的：只是接觸 介紹：我是Yuki-Luofan，目前是LainZine的新主編（中國特別版），我真是無聊

你的请求已被批准，请等待我们将你邀请加入RinLin INT Organization.
